### ISSUE TITLE
Please update gradle-wrapper.properties

### ISSUE THREAD

**Issue by IzzySoft** [v4lpt/PWG#3]
Your `gradle-wrapper.properties` has the [wrong `distributionSha256Sum`](https://github.com/v4lpt/PWG/blob/master/gradle/wrapper/gradle-wrapper.properties#L3) – that's the one from 8.0.2, which you forgot to adjust [when updating to 8.7](https://github.com/v4lpt/PWG/commit/391c0026f2dd6298c8c8fb30dac59c815eb78a6a#diff-40640fe1078ece83d7ea8fb67daacd77923a86d13447baf9769660b3b46f2ece). The correct checksum for 8.7 would be `544c35d6bd849ae8a5ed0bcea39ba677dc40f49df7d1835561582da2009b961d`.

**Comment by v4lpt** [comment]
fixed [it](https://github.com/v4lpt/PWG/commit/5cb20ffcb223abcebad0b593cadb46ff31522d03)

:)

**Comment by IzzySoft** [comment]
Thanks!
